# Generated by Django 5.1 on 2024-08-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_view_at',
            field=models.DateTimeField(null=True),
        ),
    ]
