# Generated by Django 5.1 on 2024-09-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_patient_last_view_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='centro_de_salud',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ciudad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='comuna',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='rut',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
