# Generated by Django 5.1 on 2024-09-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_patient_centro_de_salud_patient_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
