# Generated by Django 5.1 on 2024-10-04 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_patient_address_patient_email_patient_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='pacientes.patient'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medicalhistory', to='pacientes.patient'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='symptom', to='pacientes.patient'),
        ),
    ]
