# Generated by Django 5.1 on 2024-10-08 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pacientes', '0006_alter_diagnosis_patient_alter_medicalhistory_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rut', models.CharField(max_length=12, null=True, unique=True)),
                ('superintendence_number', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('commune', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('mineduc_registration_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
