runtime: python39  # O la versión que estés usando

entrypoint: bash -c "python manage.py migrate && gunicorn -b :$PORT tesis.wsgi"


handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    script: auto
